version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_chatbot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DB_JGP
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot2:
    build: .
    image: bot2
    container_name: chatbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/DB_JGP
      PGHOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3002:3002"

    command: >
      node src/config/migrate.js && 
      npm run dev"

volumes:
  postgres_data: