FROM node:lts as dependencies

WORKDIR /app

COPY package*.json ./
COPY src/config/migrate.js ./src/config/migrate.js

RUN npm install && \
    mkdir -p \
      src/solicitudes \
      src/temp && \

COPY . .